# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fca541c8eaf9292ed772041f225d865f0b3655c56ceaa1eec3ad2eb3ddf6c1051c4c63ce588a919828d6c244f12c1e82244ddca309a9ae47c0c3c98bb1013f2c

test:
  secret_key_base: d086c71532425c4592b176246f9787257e9e7f627a659612c7765fe805ceff3b23d981bb30dc0590d6c2d2db1c828b60a3c6634f50e62dbcdbe374d16f9622af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
